server:
  port: 8080

spring:
  application:
    name: service-employee
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

cqrs:
  read: ${READ_ENABLED:true}
  write: ${WRITE_ENABLED:true}

management:
  endpoints:
    enabled-by-defaults: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS