server:
  port: ${PORT:8082}

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

cqrs:
  read: ${READ_ENABLED:true}
  write: ${WRITE_ENABLED:true}

services:
  employee_url: http://localhost:8080/v1/employees
  department_url: http://localhost:8081/v1/departments

management:
  endpoints:
    enabled-by-defaults: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS