server:
  port: 8080

spring:
  application:
    name: service-organization

cqrs:
  read: ${READ_ENABLED:true}
  write: ${WRITE_ENABLED:true}

services:
  employee_url: http://service-employee-jvm:8080/v1/employees 
  department_url: http://service-department-jvm:8080/v1/departments 

management:
  endpoints:
    enabled-by-defaults: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS