version: '3.6'

networks:
  localnet:
    name: localnet
    driver: bridge

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    volumes:
      - $PWD/vols/elasticsearch_data:/usr/share/elasticsearch/data:rw              # Persistence data
    networks:
      - localnet

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - $PWD/etc/logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - localnet

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.2.0
    volumes:
      - $PWD/vols/filebeat_data:/usr/share/filebeat/data:rw                       # Persistence data
      - $PWD/etc/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash
    networks:
      - localnet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
        ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - localnet

  openzipkin:
    image: openzipkin/zipkin
    container_name: openzipkin
    hostname: openzipkin
    restart: unless-stopped
    ports:
      - 9411:9411
    networks:
      - localnet
