server:
  port: 8081

spring:
  application:
    name: service-department

cqrs:
  read: ${READ_ENABLED:true}
  write: ${WRITE_ENABLED:true}

services:
  employee_url: http://service-employee-jvm:8080/v1/employees 

management:
  endpoints:
    enabled-by-defaults: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS