server:
  port: 8081

spring:
  application:
    name: service-department
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

cqrs:
  read: ${READ_ENABLED:true}
  write: ${WRITE_ENABLED:true}

services:
  employee_url: http://localhost:8080/v1/employees 

management:
  endpoints:
    enabled-by-defaults: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS